# https://travis-ci.org/
language: python

python:
    - 2.7

install:
    - pip install coveralls

script:
    - git config --global user.email "travis@psdwatcher.com"
    - git config --global user.name "psdwatcher"
    - coverage run test.py

after_success:
    - coveralls --verbose

notifications:
  email:
    - genocidedragon@gmail.com

