# https://travis-ci.org/
language: python

python:
    - 2.7

install:
    - pip install coveralls

script:
    - git --version
    - coverage run test.py

after_success:
    - coveralls --verbose

notifications:
  email:
    - genocidedragon@gmail.com

